language: node_js
node_js:
    - 4
install:
|
    npm install -g npm@latest
    npm --version
    npm install --registry http://registry.npmjs.org
script:
    - npm run test-ci
after_script:
    - npm run coveralls
addons:
    sauce_connect:
        username: "cxtom"
        access_key: "8188dddc-e4af-432a-9a0d-9054e1e48b46"