language: node_js
node_js:
    - 4
install:
|
    npm install -g npm@latest
    npm cache clean
    npm --version
    npm install --registry http://registry.npmjs.org
script:
    - npm run test
after_script:
    - npm run coveralls